import { UserRole } from 'src/auth/enums/user-role.enum';

const ADMIN_PERMISSIONS = [
  'admin:access',
  'users:read',
  'users:update',
  'users:delete',
  'sectors:read',
  'shop:products:read',
  'shop:products:create',
  'shop:products:update',
  'shop:products:delete',
  'shop:orders:read',
  'shop:orders:update',
  'shop:promotions:read',
  'shop:promotions:create',
  'shop:promotions:update',
  'shop:promotions:delete',
  'grill:products:read',
  'grill:products:create',
  'grill:products:update',
  'grill:products:delete',
  'grill:menus:read',
  'grill:menus:create',
  'grill:menus:update',
  'grill:menus:delete',
  'grill:orders:read',
  'grill:orders:update',
  'clean:services:read',
  'clean:services:create',
  'clean:services:update',
  'clean:services:delete',
  'clean:bookings:read',
  'clean:bookings:update',
  'events:events:create',
  'events:events:update',
  'events:events:delete',
  'events:bookings:read',
  'events:bookings:update',
  'highlights:read',
  'highlights:manage',
  'settings:read',
  'settings:manage',
  'express:deliveries:read',
  'express:deliveries:update',
  'express:couriers:create',
  'express:couriers:read',
  'express:couriers:update',
  'express:couriers:delete',
  'payments:own:init',
  'payments:own:verify',
  'todo:services:read',
  'todo:services:create',
  'todo:services:update',
  'todo:services:delete',
  'todo:orders:read',
  'todo:orders:update',
];

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  [UserRole.CLIENT]: [
    'public:read',
    'profile:read',
    'profile:update',
    'orders:own:read',
    'orders:own:create',
    'payments:own:init',
    'payments:own:verify',
  ],
  [UserRole.EMPLOYEE]: [
    'public:read',
    'profile:read',
    'profile:update',
    'operations:read',
    'operations:update',
    'todo:orders:read',
    'todo:orders:update',
    'payments:own:init',
    'payments:own:verify',
  ],
  [UserRole.ADMIN]: ADMIN_PERMISSIONS,
  [UserRole.SUPER_ADMIN]: ['*', ...ADMIN_PERMISSIONS, 'sectors:manage'],
};
