export enum EventCategory {
  MARIAGE = 'MARIAGE',
  BAPTEME = 'BAPTEME',
  ANNIVERSAIRE = 'ANNIVERSAIRE',
  DEUIL = 'DEUIL',
  SOUTENANCE = 'SOUTENANCE',
  CONFERENCE = 'CONFERENCE',
  SEMINAIRE = 'SEMINAIRE',
  SURPRISE = 'SURPRISE',
}
